const dict = {
    "Lakes": "Lacs",
    "Outdoor Activities": "Activités plein air",
    "Nature": "Nature",
    "Agriculture": "Agriculture",
    "Mining": "Mines",
    "Northern": "Nordique",
    "Industry": "Industrie",
    "Hydroelectric": "Hydroélectricité",
    "Coastal": "Côtier",
    "Suburban": "Banlieue",
    "Affluent": "Aisé",
    "Waterfront": "Bord de l'eau",
    "Historic": "Historique",
    "Maple Syrup": "Sirop d'érable",
    "Scenic": "Pittoresque",
    "Cultural": "Culturel",
    "Family-Friendly": "Familial",
    "Growing": "En croissance",
    "Industrial": "Industriel",
    "Commercial": "Commercial",
    "Diverse": "Diversifié",
    "Shopping": "Magasins",
    "Planned": "Planifié",
    "Modern": "Moderne",
    "Tourism": "Tourisme",
    "Culture": "Culture",
    "Fishing": "Pêche",
    "Rural": "Rural",
    "Manufacturing": "Manufacturier",
    "Eastern Townships": "Estrie",
    "Forestry": "Foresterie",
    "Paper Mill": "Papeterie",
    "Aviation": "Aviation",
    "Transport Hub": "Hub transport",
    "Affordable": "Abordable",
    "Unique Architecture": "Architecture unique",
    "Border City": "Frontalier",
    "Government Jobs": "Gouvernement",
    "Bilingual": "Bilingue",
    "Music": "Musique",
    "Regional Hub": "Hub régional",
    "Indigenous": "Autochtone",
    "Arctic": "Arctique",
    "Agricultural": "Agricole",
    "Lakeside": "Bord de lac",
    "Community": "Communauté",
    "Recreation": "Loisirs",
    "Heritage": "Patrimoine",
    "Wilderness": "Nature sauvage",
    "Riverside": "Bord de rivière",
    "Commuter City": "Ville dortoir",
    "Transit-Oriented": "Axé transport",
    "South Shore": "Rive-Sud",
    "Transport": "Transport",
    "Wind Energy": "Éolien",
    "Aerospace": "Aérospatiale",
    "Gateway": "Porte d'entrée",
    "Central": "Central",
    "Ski Resort": "Station de ski",
    "Metropolitan": "Métropolitain",
    "Cultural Hub": "Pôle culturel",
    "University City": "Universitaire",
    "Residential": "Résidentiel",
    "Island": "Île",
    "Port City": "Portuaire",
    "Provincial Capital": "Capitale",
    "French": "Francophone",
    "Maritime": "Maritime",
    "Education": "Éducation",
    "Research": "Recherche",
    "Fjords": "Fjords",
    "Economic Hub": "Pôle économique",
    "Beauce": "Beauce",
    "Military": "Militaire",
    "Mountain Access": "Accès montagne",
    "Equestrian": "Équestre",
    "Innovation": "Innovation",
    "Mining Heritage": "Patrimoine minier",
    "Historical": "Historique",
    "Resources": "Ressources",
    "Energy": "Énergie",
    "Sustainable": "Durable",
    "Quality of Life": "Qualité de vie",
    "Prestigious": "Prestigieux",

    "A city surrounded by lakes and known for outdoor activities.": "Ville entourée de lacs et réputée pour ses activités de plein air.",
    "Agricultural and mining center in northern Québec.": "Centre agricole et minier dans le nord du Québec.",
    "An industrial city with impressive hydroelectric infrastructure.": "Ville industrielle avec d'impressionnantes infrastructures hydroélectriques.",
    "Affluent suburban community on the West Island of Montréal.": "Communauté de banlieue huppée de l'Ouest-de-l'Île de Montréal.",
    "Historic town in the Beauce region known for maple syrup production.": "Ville historique de la Beauce connue pour le sirop d'érable.",
    "Industrial city with significant hydroelectric facilities.": "Ville industrielle avec d'importantes installations hydroélectriques.",
    "Scenic city at the foot of Mont Saint-Hilaire.": "Ville pittoresque au pied du mont Saint-Hilaire.",
    "Growing suburban city with excellent family amenities.": "Ville de banlieue en croissance, idéale pour les familles.",
    "Industrial and commercial hub north of Montréal.": "Pôle industriel et commercial au nord de Montréal.",
    "Historic and affluent suburb with strong industrial sector.": "Banlieue historique et aisée avec un fort secteur industriel.",
    "A diverse suburban city known for its shopping and multicultural community.": "Ville de banlieue diversifiée, connue pour ses commerces et sa communauté multiculturelle.",
    "Modern suburban community with planned developments.": "Communauté de banlieue moderne et développements urbains structurés.",
    "Seaside resort town with strong cultural scene.": "Station balnéaire avec une forte scène culturelle.",
    "Historic fort town with beautiful waterfront.": "Ville fortifiée historique avec un magnifique bord de l'eau.",
    "Coastal town with fishing and tourism economy.": "Ville côtière vivant de la pêche et du tourisme.",
    "Suburban city with rich history and natural areas.": "Ville de banlieue avec une riche histoire et des espaces naturels.",
    "Agricultural town known for dairy products and tourism.": "Ville agricole reconnue pour ses produits laitiers et le tourisme.",
    "A small city in the Eastern Townships with manufacturing focus.": "Petite ville de l'Estrie axée sur l'industrie manufacturière.",
    "Paper mill town with strong forestry industry.": "Ville papetière avec une forte industrie forestière.",
    "Industrial town with paper mill heritage.": "Ville industrielle au patrimoine lié à la papeterie.",
    "Home to Montréal International Airport with strong aviation sector.": "Hôte de l'Aéroport international de Montréal, secteur aérien fort.",
    "An industrial city with a growing economy and famous for poutine.": "Ville industrielle en croissance économique, célèbre pour la poutine.",
    "Northern mining town with unique windbreak wall architecture.": "Ville minière nordique à l'architecture de mur brise-vent unique.",
    "Coastal city at the tip of the Gaspé Peninsula.": "Ville côtière à la pointe de la péninsule gaspésienne.",
    "A bilingual city bordering Ottawa, offering unique opportunities in both Québec and Ontario.": "Ville bilingue frontalière avec Ottawa, aux portes du Québec et de l'Ontario.",
    "A family-friendly city known for its zoo and quality of life.": "Ville conviviale connue pour son zoo et sa qualité de vie.",
    "Cultural center with strong music tradition.": "Centre culturel avec une forte tradition musicale.",
    "Largest northern village in Nunavik region.": "Le plus grand village nordique de la région du Nunavik.",
    "Historic industrial town with agricultural surroundings.": "Ville industrielle historique avec des environs agricoles.",
    "Lakeside town rebuilding with community focus.": "Ville au bord du lac en pleine reconstruction axée sur la communauté.",
    "Historic suburban city with preserved old quarter.": "Ville de banlieue historique avec un quartier ancien préservé.",
    "Forestry center with vast wilderness territory.": "Centre forestier avec un vaste territoire sauvage.",
    "A suburban city north of Montréal with family-friendly neighborhoods and extensive shopping.": "Ville de banlieue au nord de Montréal, quartiers familiaux et nombreux commerces.",
    "A scenic city across the St. Lawrence from Québec City, offering suburban comfort with urban proximity.": "Ville pittoresque face à Québec, offrant confort de banlieue et proximité urbaine.",
    "A tourist destination known for its lakes and mountains.": "Destination touristique réputée pour ses lacs et montagnes.",
    "Forestry and tourism center with strong Indigenous presence.": "Centre forestier et touristique avec une forte présence autochtone.",
    "Growing suburban city with excellent transport links.": "Ville de banlieue en croissance avec d'excellentes liaisons de transport.",
    "A coastal city known for its shrimp fishing and wind energy.": "Ville côtière connue pour la pêche à la crevette et l'énergie éolienne.",
    "Fast-growing city with aerospace industry and agriculture.": "Ville en forte croissance, aérospatiale et agriculture.",
    "Gateway to northern Québec with forestry economy.": "Porte d'entrée vers le nord du Québec, économie forestière.",
    "Affluent planned community in central Montréal.": "Communauté planifiée huppée au centre de Montréal.",
    "Scenic city with famous mountain and apple orchards.": "Ville pittoresque avec de célèbres montagnes et vergers de pommiers.",
    "A premier ski resort destination with year-round tourism.": "Station de ski de premier plan, tourisme à l'année.",
    "The largest city in Québec, known for its vibrant culture, food scene, and bilingual environment.": "La plus grande métropole du Québec, vibrante culture, gastronomie et environnement bilingue.",
    "Iconic tourist destination known for Rocher Percé.": "Destination touristique iconique connue pour le Rocher Percé.",
    "Residential community on Île Perrot.": "Communauté résidentielle sur l'Île Perrot.",
    "Historic West Island suburb with strong commercial sector.": "Banlieue historique de l'Ouest-de-l'Île avec un fort secteur commercial.",
    "Industrial port city with mining and forestry sectors.": "Ville portuaire industrielle, secteurs minier et forestier.",
    "The capital city of Québec with beautiful historic architecture and strong French heritage.": "La capitale du Québec avec une belle architecture historique et un fort héritage francophone.",
    "A suburban community with excellent family amenities and riverside location.": "Communauté aux excellentes commodités familiales, située au bord de l'eau.",
    "A maritime city with strong education and research sectors.": "Ville maritime avec de forts secteurs d'éducation et de recherche.",
    "A scenic city known for whale watching and maritime tourism.": "Ville pittoresque connue pour l'observation des baleines et le tourisme maritime.",
    "A mining and cultural center in northwestern Québec.": "Centre minier et culturel dans le nord-ouest du Québec.",
    "A northern city surrounded by natural beauty and outdoor recreation opportunities.": "Ville nordique entourée par la nature avec nombreuses opportunités de loisirs de plein air.",
    "Affluent suburb of Québec City with industrial park.": "Banlieue huppée de la ville de Québec avec parc industriel.",
    "Growing suburban community with agricultural heritage.": "Communauté de banlieue en croissance avec un héritage agricole.",
    "Affluent suburb with ski hill and national park.": "Banlieue aisée avec station de ski et parc national.",
    "Growing suburban city with railway heritage.": "Ville de banlieue en croissance avec un héritage ferroviaire.",
    "A historic suburban city with agricultural heritage.": "Ville de banlieue historique avec un héritage agricole.",
    "Economic hub of the Beauce region with strong manufacturing.": "Pôle économique de la région de la Beauce avec une forte base manufacturière.",
    "Agricultural technology and food research center.": "Centre de technologie agricole et de recherche alimentaire.",
    "A military and industrial center with rich history and beautiful waterfront.": "Centre militaire et industriel avec une riche histoire et un magnifique front de mer.",
    "A gateway to the Laurentians with both urban amenities and outdoor recreation.": "Porte d'entrée des Laurentides, commodités urbaines et loisirs de plein air.",
    "Affluent suburb with historic village atmosphere.": "Banlieue cossue avec une atmosphère de village historique.",
    "Equestrian-focused community with rural character.": "Communauté au caractère rural axée sur le domaine équestre.",
    "Growing community with mix of rural and suburban areas.": "Communauté en croissance avec un mélange de zones rurales et de banlieue.",
    "Popular tourist destination in the Laurentians with ski resorts.": "Destination touristique populaire dans les Laurentides, avec stations de ski.",
    "A waterfront city with industrial heritage and scenic canals.": "Ville au bord de l'eau avec un héritage industriel et des canaux pittoresques.",
    "A major seaport city with strong industrial and tourism sectors.": "Ville portuaire majeure avec de forts secteurs industriels et touristiques.",
    "A city reinventing itself with focus on innovation and outdoor activities.": "Ville qui se réinvente, axée sur l'innovation et les activités de plein air.",
    "A vibrant university city with a perfect blend of urban amenities and natural surroundings.": "Ville universitaire effervescente, mélange parfait de commodités urbaines et de nature.",
    "An industrial port city at the confluence of two major rivers.": "Hub industriel et portuaire à la confluence de deux grandes rivières.",
    "A rapidly growing suburban city with historic charm and modern amenities.": "Ville de banlieue en croissance rapide, entre charme historique et modernité.",
    "Historic mining city transitioning to new industries.": "Ancienne ville minière en transition vers de nouvelles industries.",
    "A historic city known for its cultural festivals and industrial heritage.": "Ville historique réputée pour ses festivals culturels et son patrimoine industriel.",
    "A gold mining city with strong resource-based economy.": "Ville minière (or) avec une forte économie basée sur les ressources.",
    "Industrial city with focus on energy and chemical sectors.": "Ville industrielle axée sur les secteurs de l'énergie et de la chimie.",
    "Fast-growing suburban city with major commercial development.": "Ville de banlieue en forte croissance et développement commercial majeur.",
    "Known as the cradle of sustainable development in Québec.": "Reconnue comme le berceau du développement durable au Québec.",
    "Prestigious enclave known for heritage architecture.": "Enclave prestigieuse reconnue pour son architecture patrimoniale.",

    // Incomplete descriptions from previous parse might be here depending on truncation,
    // Provide a few variations:
    "Affluent suburban community on Montréal's West Island.": "Importante communauté de banlieue dans l'Ouest-de-l'Île de Montréal.",
    "A major suburb on Montréal's South Shore with excellent transit connections.": "Banlieue majeure de la Rive-Sud de Montréal avec d'excellentes liaisons de transport."
};

const fs = require('fs');
let s = fs.readFileSync('src/data/cities.ts', 'utf-8');

for (const [eng, fr] of Object.entries(dict)) {
    s = s.split(`'${eng}'`).join(`'${fr}'`);
}

// And finally replacing any string containing population to Population is not needed since they already match.
fs.writeFileSync('src/data/cities.ts', s);
console.log('Done replacement');
